// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Geometry$Inversion = require("./Geometry.bs.js");

var defaultColor = "black";

function setDefaultStrokeStyle(ctx) {
  ctx.strokeStyle = defaultColor;
  return /* () */0;
}

function setDefaultFillStyle(ctx) {
  ctx.fillStyle = defaultColor;
  return /* () */0;
}

function circumference(param, $staropt$star, canvas) {
  var centre = param[/* centre */0];
  var color = $staropt$star !== undefined ? $staropt$star : defaultColor;
  var ctx = canvas.getContext("2d");
  ctx.strokeStyle = color;
  ctx.beginPath();
  ctx.arc(centre[0], centre[1], param[/* radius */1], 0, Geometry$Inversion.pi * 2, true);
  ctx.stroke();
  ctx.closePath();
  ctx.strokeStyle = defaultColor;
  return /* () */0;
}

function segment(param, $staropt$star, canvas) {
  var match = param[1];
  var match$1 = param[0];
  var color = $staropt$star !== undefined ? $staropt$star : defaultColor;
  var ctx = canvas.getContext("2d");
  ctx.strokeStyle = color;
  ctx.beginPath();
  ctx.moveTo(match$1[0], match$1[1]);
  ctx.lineTo(match[0], match[1]);
  ctx.stroke();
  ctx.closePath();
  ctx.strokeStyle = defaultColor;
  return /* () */0;
}

function line(param, $staropt$star, canvas) {
  var match = param[1];
  var match$1 = param[0];
  var a2 = match$1[1];
  var a1 = match$1[0];
  var color = $staropt$star !== undefined ? $staropt$star : defaultColor;
  var ctx = canvas.getContext("2d");
  var canvasWidth = canvas.width;
  var canvasHeight = canvas.height;
  var d1 = match[0] - a1;
  var d2 = match[1] - a2;
  var canvasSize = Geometry$Inversion.distance(/* tuple */[
        0,
        0
      ], /* tuple */[
        canvasWidth,
        canvasHeight
      ]);
  ctx.strokeStyle = color;
  ctx.beginPath();
  ctx.moveTo(a1 - d1 * canvasSize, a2 - d2 * canvasSize);
  ctx.lineTo(a1 + d1 * canvasSize, a2 + d2 * canvasSize);
  ctx.stroke();
  ctx.closePath();
  ctx.strokeStyle = defaultColor;
  return /* () */0;
}

function point(param, $staropt$star, canvas) {
  var color = $staropt$star !== undefined ? $staropt$star : defaultColor;
  var ctx = canvas.getContext("2d");
  ctx.fillStyle = color;
  ctx.beginPath();
  ctx.arc(param[0], param[1], 1, 0, Geometry$Inversion.pi * 2, true);
  ctx.fill();
  ctx.closePath();
  ctx.fillStyle = defaultColor;
  return /* () */0;
}

function clear(canvas) {
  canvas.getContext("2d").clearRect(0, 0, canvas.width, canvas.height);
  return /* () */0;
}

exports.defaultColor = defaultColor;
exports.setDefaultStrokeStyle = setDefaultStrokeStyle;
exports.setDefaultFillStyle = setDefaultFillStyle;
exports.circumference = circumference;
exports.segment = segment;
exports.line = line;
exports.point = point;
exports.clear = clear;
/* Geometry-Inversion Not a pure module */
