// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Draw$Inversion = require("./Draw.bs.js");

var canvas = document.getElementById("screen");

var screen = canvas.getContext("2d");

Draw$Inversion.circle(/* record */[
      /* x */100,
      /* y */100
    ], 40, screen);

Draw$Inversion.segment(/* record */[
      /* x */100,
      /* y */100
    ], /* record */[
      /* x */300,
      /* y */300
    ], screen);

exports.canvas = canvas;
exports.screen = screen;
/* canvas Not a pure module */
